extends: default

rules:
# 80 chars should be enough, but don't fail if a line is longer
  line-length: disable
# Head of document
  document-start: disable
# don't bother me with this rule
  indentation: disable
# don't bother me with this rule
  trailing-spaces: disable
# don't bother me with this rule
  truthy:
    level: warning
    ignore: |
      .github/workflows/*.yaml
# Use this rule to set a maximal number of allowed consecutive blank lines
  empty-lines:
    max: 1
    max-start: 0
    max-end: 0
# Use this rule to prevent multiple entries with the same key in mappings
key-duplicates:
    forbid-duplicated-merge-keys: false