name: Ka0s JSON Lint

on:
  workflow_dispatch: # Workflow manualmente
    inputs:
      kaos-origin:
        description: 'Dispatcher Workflow Run ID'
        default: ""
        required: true
      kaos-files:
        description: 'Files Involved'
        default: ""
        required: true
      kaos-issue-id:
        description: 'Issue ID'
        default: "Kaos Issue ID"
        required: true
  
permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write

env:
  KAOS_MODULE: "[Ka0S] JSONLINT"
  GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
  PATH_RESUME: "core/results/"
  FILE_ERROR: ""
  USER_NAME: ${{ secrets.KAOS_USER_NAME }}
  USER_EMAIL: ${{ secrets.KAOS_USER_EMAIL }}

jobs:
  json-lint-process:
    runs-on: 
      group: kaos-jsonlint

    steps:
      - id: repo # Checkout the repository to get the information of the commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_TOKEN }}
    
      - id: install-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
  
      - id: check-json
        run: |
            # Invocamos la primera comprobación de base, sino se supera el proceso no continua
            git config --global user.name '${{ env.USER_NAME }}'
            git config --global user.email '${{ env.USER_EMAIL}}'
            git pull
            # Extraemos el nombre del fichero
            file_name=$(basename "${{ github.event.inputs.kaos-files }}")
            # Generamos el fichero de resultados vacio
            touch ${{ env.PATH_RESUME }}jsonlint-results-${{ github.run_id }}.txt
            # Realizamos el check del documento json 
            # Este paso lo vamos a tener de ejemplo para ver la integración de codigo en el propio workflow
            python - <<EOF
            import json

            def validate_json(file_path):
                try:
                    with open(file_path, 'r') as file:
                        data = json.load(file)
                    return True, None
                except json.JSONDecodeError as e:
                    return False, str(e)

            def write_errors_to_file(errors, output_file, input_file):
                with open(output_file, 'w') as file:
                    file.write(f"Los errores descritos en este documento han sido encontrados en {input_file}\\n")
                    file.write(errors)

            def main():
                input_file = '${{ github.event.inputs.kaos-files }}'  # Cambia esto por el nombre de tu archivo JSON
                output_file = '${{ env.PATH_RESUME }}jsonlint-results-${{ github.run_id }}.txt'
            
                is_valid, error_message = validate_json(input_file)
                if not is_valid:
                    write_errors_to_file(error_message, output_file, input_file)
                
            main()
            EOF
            git add ${{ env.PATH_RESUME }}jsonlint-results-${{ github.run_id }}.txt
            git commit -m "Generated file ${{ env.PATH_RESUME }}jsonlint-results-${{ github.run_id }}.txt"
            git push
            # Check if exist errors in file
            if [ ! -s ${{ env.PATH_RESUME }}jsonlint-results-${{ github.run_id }}.txt ]; then
              echo "File ${{ env.PATH_RESUME }}jsonlint-results-${{ github.run_id }}.txt is empty and is content correct"
              KAOS_ISSUE_BODY="The json lint process ${{ github.event.inputs.kaos-origin }} launch the check ${{ github.run_id }} over file ${{ github.event.inputs.kaos-files }} and its result has been SUCCESS. Please MERGE"
              gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-title="" -f kaos-issue-body="$KAOS_ISSUE_BODY" -f kaos-issue-actions=comment -f kaos-issue-tag="" -f kaos-issue-id=${{ github.event.inputs.kaos-issue-id }}
            else
              echo "File ${{ env.PATH_RESUME }}jsonlint-results-${{ github.run_id }}.txt is not empty and is content not correct and write commit info"
              echo "FILE_ERROR=${{ env.PATH_RESUME }}jsonlint-results-${{ github.run_id }}.txt" >> $GITHUB_ENV
              KAOS_ISSUE_BODY="The json lint process ${{ github.event.inputs.kaos-origin }} launch the check ${{ github.run_id }} over file ${{ github.event.inputs.kaos-files }} and its result has been FAILED, please check ${{ env.PATH_RESUME }}jsonlint-results-${{ github.run_id }}.txt and solved it"
              gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-title="" -f kaos-issue-body="$KAOS_ISSUE_BODY" -f kaos-issue-actions=comment -f kaos-issue-tag="" -f kaos-issue-id=${{ github.event.inputs.kaos-issue-id }} 
            fi
            
  handle_failure:
    runs-on: 
      group: kaos-jsonlint
    needs: [json-lint-process]
    if: ${{ failure() }}
    steps:
      - id: check-execution
        env:
          GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
        run: |
          echo "Error detected in ${{ env.KAOS_MODULE }}, creating issue..."
          KAOS_ISSUE_TITLE="${{ env.KAOS_MODULE }} Action Failed: ${{ github.workflow }}"
          KAOS_ISSUE_BODY=$(cat <<'EOF'
          An error occurred in the ${{ env.KAOS_MODULE }} Action workflow **${{ github.workflow }}**.
          **${{ env.KAOS_MODULE }}  Message:**
          El error ha sido en : ${{  github.run_id }}
          ejecute este comando en su consola y podrá consultar el fallo del trabajo
          gh run view ${{  github.run_id }} --log-failed
          y compruebe el fichero: ${{ env.FILE_ERROR}}
          \`\`\`
          **Please check the job logs for ${{ secrets.KAOS_ACTIONS_URL }}${{ github.run_id }}**
          \`\`\`
          **Workflow Name:** ${{ github.workflow }}
          **Job Name:** ${{ github.job }}
          **Run ID:** ${{ github.run_id }}
          **Run Number:** ${{ github.run_number }}
          **Repository:** ${{ github.repository }}
          **Branch:** ${{ github.ref }}
          **Commit:** ${{ github.sha }}
          Please investigate the issue.
          EOF
          )
          gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-title="$KAOS_ISSUE_TITLE" -f kaos-issue-body="$KAOS_ISSUE_BODY" -f kaos-issue-actions=create -f kaos-issue-tag="bug"   

  handle_success:
     runs-on: 
       group: kaos
     needs: [job-core, job-compliance, job-security, job-observability, job-codescan, job-flows]
     if: ${{ success() }}
     steps:
       - id: check-execution
         env:
           GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
         run: |
               echo "Error detected in ${{ env.KAOS_MODULE }}, creating issue..."
               KAOS_ISSUE_TITLE="${{ env.KAOS_MODULE }} Action Failed: ${{ github.workflow }}"
               KAOS_ISSUE_BODY=$(cat <<'EOF'
               **${{ env.KAOS_MODULE }} Message: run_id ${{ github.workflow }}**
               Compliance: ${{ needs.job-compliance.outputs.KAOS_COMPLIANCE_STATUS }}
               Security: ${{ needs.job-security.outputs.KAOS_SECURITY_STATUS }}
               Observability: ${{ needs.job-observability.outputs.KAOS_OBSERVABILITY_STATUS }}
               CodeScan: ${{ needs.job-codescan.outputs.KAOS_CODESCAN_STATUS }}
               Flow: ${{ needs.job-flows.outputs.KAOS_FLOWS_STATUS }}
               EOF
               )
               gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-body="$KAOS_ISSUE_BODY"  -f kaos-issue-id=${{ needs.job-core.outputs.KAOS_NUMBER }} -f kaos-issue-actions=comment 