name: Context testing
on: 
    workflow_dispatch:

jobs:
  dump-github-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
            echo "$GITHUB_CONTEXT" >> GITHUB_OUTPUT
  dump-job-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump job context
        id: job
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
            echo "$JOB_CONTEXT"
  dump-steps-context:
      runs-on: ubuntu-latest     
      steps:
      - name: Dump steps context
        id: steps
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: |
            echo "$STEPS_CONTEXT"

  dump-runner-context:
      runs-on: ubuntu-latest     
      steps:
      - name: Dump runner context
        id: runner
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: |
            echo "$RUNNER_CONTEXT" >> $GITHUB_OUTPUT

  handler-exception:
        runs-on: ubuntu-latest
        steps:
        - name: Exception Handler
          id: handler
          env:
            STEPS_CONTEXT: ${{ toJson(steps) }}
          run: |
            echo "$STEPS_CONTEXT"

