name: Check

on:
  workflow_dispatch:
    branches:
      - feature

permissions:
  contents: write
  actions: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set execution date-time variable
        id: set_datetime
        run: echo "datetime=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Validate YAML Workflows
        id: validate-yaml
        run: |
          echo "Resume Check YAML" > ./results/Resume-check-yaml-${{ env.datetime }}.txt
          for file in .github/workflows/*.yaml; do
          if ! yq e '. | type == "object"' "$file"; then
            echo "Error en archivo $file - Version NO VALIDA" >> ./results/Resume-check-yaml-${{ env.datetime }}.txt
          else
            echo "Archivo $file - Version OK" >> ./results/Resume-check-yaml-${{ env.datetime }}.txt
          fi
          done
      
      - name: Subir resultados a GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: Resume-check-yaml
          path: ./results/Resume-check-yaml-${{ env.datetime }}.txt
      
      - name: Commit and Push Results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add results/*.txt
          git commit -m "Build: New version to TEST of GitHub Actions ${{ env.CLEAN_BRANCH_NAME }}"
          git push origin feature
  
      - name: Trigger Test
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Test
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: feature