name: Ka0S Deployment
on:
  workflow_dispatch:
    inputs:
      kaos-org-name:
        description: 'Organization Name'
        default: ""
        required: true
      kaos-repo-name:
        description: 'Repository Name'
        default: ""
        required: false
      kaos-project-name:
        description: 'Project Name'
        default: ""
        required: false
      kaos-issue-id:
        description: 'Issue ID'
        default: ""
        required: true

permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write

env:
  KAOS_MODULE: "[Ka0S] Deployment"
  GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
  BRANCH_NAME: ${{ github.ref }}
  KAOS_PATH_RESUME: "core/results/"
  KAOS_REPO: "/actions-runner/_work/kaos/kaos"
  KAOS_STEP_MODULE: ""
  KAOS_CODE: ""

jobs:
  jobs-core:
    runs-on: 
      group: kaos-init
    steps:
      - id: repo
        name: Check Repository
        if: ${{ success() }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_TOKEN }}

      - id: message
        name: Message
        if: ${{ success() }}
        run: |
          echo "Init repository"
          gh issue comment $KAOS_ISSUE_NUMBER -b "Se ha iniciado el repositorio"

  jobs-project:
    runs-on: 
      group: kaos
    needs: jobs-core
    steps:
      - id: project
        name: Create project
        if: ${{ success() }}
        run: |
          echo "Create project"
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh project create --owner ${{ github.event.inputs.kaos-org-name }} --title ${{ github.event.inputs.kaos-project-name }} --format json

      - id: assignpro
        name: Assign project to repo
        if: ${{ success() }}
        run: |
          echo "Assign project to repo"
          PROJECT_NUMBER=$(gh project list --owner ${{ github.event.inputs.kaos-org-name }} --json number --jq '..number')
          gh project link $PROJECT_NUMBER --owner ${{ github.event.inputs.kaos-org-name }} --repo ${{ github.event.inputs.kaos-org-name }}/${{ github.event.inputs.kaos-repo-name }}

  jobs_repo:
    runs-on:
      group: kaos
    needs: jobs-project
    steps:
      - id: repo
        name: Clone Repo
        if: ${{ success() }}
        run: |
          echo "Clone Repo"
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh repo clone ${{ github.event.inputs.kaos-org-name }}/${{ env.KAOS_REPO }}

      - id: assignrep
        name: Assign respository to Organization & Proyect
        if: ${{ success() }}
        run: |
          echo "Assign repo to organization and proyect"
          PROJECT_NUMBER=$(gh project list --owner ${{ github.event.inputs.kaos-org-name }} --json number --jq '..number')
          gh project link $PROJECT_NUMBER --owner ${{ github.event.inputs.kaos-org-name }} --repo ${{ github.event.inputs.kaos-org-name }}/${{ env.KAOS_REPO }}
