name: Ka0s Execution

on:
  issues:
    types: [opened]
permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write
env:
  KAOS_MODULE: "[Ka0S] Execution"
  GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
  BRANCH_NAME: ${{ github.ref }}
  KAOS_PATH_RESUME: "core/results/"
  KAOS_REPO: "/actions-runner/_work/kaos/kaos"
  KAOS_STEP_MODULE: ""
  KAOS_CODE: ""
  KAOS_ISSUE_NUMBER: ${{ github.event.issue.number }}
  KAOS_ISSUE_TITLE: ${{ github.event.issue.title }}
  KAOS_ISSUE_BODY: ${{ github.event.issue.body }}
  KAOS_ISSUE_LABELS: ${{ github.event.issue.labels }}
  KAOS_ISSUE_USER: ${{ github.event.issue.user }}

jobs:
  check-issue:
    runs-on: kaos-execution
    steps:
      - id: check-info
        name: Check Info
        if: startsWith(github.event.issue.title, '[E]')
        run: |
            echo "Check issue for execution $KAOS_ISSUE_NUMBER"
  check-data:
    runs-on: kaos-execution
    needs: check-issue
    steps:
      - id: data
        name: Check data
        if: ${{ success() }}
        run: |
            echo "Check data"
            gh issue comment $KAOS_ISSUE_NUMBER -b "Se han comprobado los datos" 
  show-data:
    runs-on: kaos-execution
    needs: [check-data, check-issue]
    steps:
      - id: show
        name: Show data
        if: ${{ success() }}
        run: |
          echo "Datos de la ejecución"
          echo "KAOS_ISSUE_NUMBER: $KAOS_ISSUE_NUMBER" 
          echo "KAOS_ISSUE_TITLE: $KAOS_ISSUE_TITLE"
          echo "KAOS_ISSUE_BODY: $KAOS_ISSUE_BODY"
          echo "KAOS_ISSUE_LABELS: $KAOS_ISSUE_LABELS"
          echo "KAOS_ISSUE_USER: $KAOS_ISSUE_USER"
          gh issue comment $KAOS_ISSUE_NUMBER -b "Se han mostrado los datos"     
  init-repo:
    runs-on: kaos-execution
    needs: [check-issue, check-data]
    steps:
      - id: repo
        name: Checkout repository
        if: ${{ success() }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_TOKEN }}
      - id: message
        name: Message
        if: ${{ success() }}
        run: |
          echo "Init repository"
          gh issue comment $KAOS_ISSUE_NUMBER -b "Se ha iniciado el repositorio"
  start-execution:
    runs-on: kaos-execution
    needs: [check-issue, check-data, init-repo]
    outputs:
        KAOS_EXECUTION_RESULT: ${{ steps.execution.outputs.KAOS_EXECUTION_RESULT }}
        KAOS_EXECUTION_STATUS: ${{ steps.execution.outputs.KAOS_EXECUTION_STATUS }}
    steps:
      - id: execution
        name: Start execution
        if: ${{ always() }}
        run: |
          # Sección donde definimos como será la ejecución
          echo "Start execution"
          echo "KAOS_EXECUTION_RESULT=fichero_de_resultado" >> $GITHUB_OUTPUT
          echo "KAOS_EXECUTION_STATUS=success" >> $GITHUB_OUTPUT
          gh issue comment $KAOS_ISSUE_NUMBER -b "Se han lanzado la ejecución"
  end-execution:
    runs-on: kaos-execution
    needs: [check-issue, check-data, init-repo, start-execution]
    steps:
      - id: end
        name: End execution
        if: ${{ always() }}
        run: |
          echo "End execution"
          gh issue comment $KAOS_ISSUE_NUMBER -b "La ejecución ha finalizado con el resultado ${{ needs.start-execution.outputs.KAOS_EXECUTION_STATUS }}"
          gh issue comment $KAOS_ISSUE_NUMBER -b "Se añade el fichero de resultados" -F "${{ needs.start-execution.outputs.KAOS_EXECUTION_RESULT }}"
  handle-success:
    runs-on: 
      group: kaos-execution
    needs: [check-issue, check-data, init-repo, start-execution, end-execution]
    if: ${{ success() }}
    steps: 
      - id: handle-success-execution
        run: |
          # Añadimos a cada paso el mensaje de éxito incluido en la issue original
          echo "${{ env.KAOS_MODULE }} Success in runid ${{ github.run_id }} initiated by $KAOS_ISSUE_USER trouhg issue number $KAOS_ISSUE_NUMBER."
          echo "La ejecución solicitada en el issue #$KAOS_ISSUE_NUMBER ha sido completada con éxito."
          echo "El log de la ejecucion se encuentra en ${{ secrets.KAOS_ACTIONS_URL }}${{ github.run_id }}"
          echo "Se añade el log de la ejecución al issue #$KAOS_ISSUE_NUMBER"
          echo "Se procede a cerrar la issue #$KAOS_ISSUE_NUMBER"
          gh issue comment $KAOS_ISSUE_NUMBER -b "Aquí podemos añadir los resultados de la ejecución de la issue antes de cerrarla"
  handle_failure:
      runs-on: 
        group: kaos-execution
      needs: [check-issue, check-data, init-repo]
      if: ${{ failure() }} 
      steps: 
        - id: check-execution
          run: |
            echo "Error detected in ${{ env.KAOS_MODULE }}, creating issue..."
            KAOS_TITLE="${{ env.KAOS_MODULE }} Module failed in ${{ github.run_id }}"
            KAOS_BODY=$(cat <<'EOF'
            An error occurred in the execution Action workflow RunID: **${{ github.run_id }}**.
            Initiated by #$KAOS_ISSUE_USER from issue number #$KAOS_ISSUE_NUMBER
            **${{ env.KAOS_MODULE }}  Message:**
            El error ha sido en : ${{  github.run_id }}
            ejecute este comando en su consola y podrá consultar el fallo del trabajo
            gh run view ${{  github.run_id }} --log-failed
            \`\`\`
            **La información de la ejecución ${{ secrets.KAOS_ACTIONS_URL }}${{ github.run_id }}**
            \`\`\`
            **Solicitado por:** $KAOS_ISSUE_USER
            **Número de ejecución:** $KAOS_ISSUE_NUMBER
            **Título:** ${{ env.KAOS_ISSUE_TITLE }}
            **Datos de la ejecución:** ${{ env.KAOS_ISSUE_TITLE }}
            **Tipo de Ejecución:** $KAOS_ISSUE_LABELS
            Please investigate the issue.
            EOF
            )
            # Creamos la issue dado que ha fallado el modulo principal
            gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-title="$KAOS_TITLE" -f kaos-issue-body="$KAOS_BODY" -f kaos-issue-actions=create -f kaos-issue-tag="bug" -f kaos-user-start="$KAOS_ISSUE_USER"
            # Añadimos el comentario a la issue que dispara el proceso
            KAOS_ISSUE_BODY="OPS¡ se ha producido un error en el proceso (${{ env.KAOS_MODULE }}) lanzado desde (#$KAOS_ISSUE_NUMBER) en la ejecución (${{ github.run_id }}) y esto ha generado una issue con el titulo ($KAOS_TITLE)"
            gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-body="$KAOS_BODY" -f kaos-issue-actions=comment -f kaos-issue-tag="bug" -f kaos-issue-id=$KAOS_ISSUE_NUMBER
