name: Git Information

on:
  workflow_dispatch:
  
permissions:
  contents: write
  actions: write

jobs:
  git-informacion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Obtener información commit
        id: obtener-informacion
        run: |
          # Obtenemos la información del commit actual
          echo "COMMIT_ID=${{ github.sha }}" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
          echo "AUTHOR=$(git log -1 --format=%an)" >> $GITHUB_ENV
          echo "DATE=$(git log -1 --format=%cd)" >> $GITHUB_ENV
      
          # Obtenemos la lista de archivos cambiados en el commit
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed-files.txt
      
          # Obtenemos la información del branch actual
          echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "BRANCH_DESCRIPTION=$(git describe --tags --always 2>/dev/null || git rev-parse --short HEAD)" >> $GITHUB_ENV
      
        
      - name: Mostrar contenido de variables
        run: |
          # Obtenemos el contenido de las variables guardadas
          echo "Variables guardadas:"
          echo "COMMIT_ID: ${{ env.COMMIT_ID }}"
          echo "COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}"
          echo "AUTHOR: ${{ env.AUTHOR }}"
          echo "DATE: ${{ env.DATE }}"
          echo "CHANGED_FILES: ${{ changed-files.txt}}"
          echo "BRANCH_NAME: ${{ env.BRANCH_NAME }}"
          echo "BRANCH_DESCRIPTION: ${{ env.BRANCH_DESCRIPTION }}"