name: Git Information

on:
  workflow_dispatch:
  
permissions:
  contents: write
  actions: write

jobs:
  git-informacion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Obtener información commit
        id: obtener-informacion
        run: |
          # Obtenemos la información del commit actual
          COMMIT_ID=$(git rev-parse HEAD)
          COMMIT_MESSAGE=$(git log -1 --format=%s)
          AUTHOR=$(git log -1 --format=%an)
          DATE=$(git log -1 --format=%cd)

          # Obtenemos la lista de archivos cambiados en el commit
          CHANGED_FILES=$(git diff --cached --name-only)

          # Obtenemos la información del branch actual
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          BRANCH_DESCRIPTION=$(git describe --tags --always 2>/dev/null || git rev-parse --short HEAD)

          # Almacenamos la información en variables
          echo "COMMIT_ID: $COMMIT_ID" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE: $COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "AUTHOR: $AUTHOR" >> $GITHUB_ENV
          echo "DATE: $DATE" >> $GITHUB_ENV
          echo "CHANGED_FILES: $CHANGED_FILES" >> $GITHUB_ENV
          echo "BRANCH_NAME: $BRANCH_NAME" >> $GITHUB_ENV
          echo "BRANCH_DESCRIPTION: $BRANCH_DESCRIPTION" >> $GITHUB_ENV

      - name: Almacenar información en variables
        id: almacenar-informacion
        run: |
          # Obtenemos las variables de la acción anterior
          COMMIT_ID=$(echo "$GITHUB_ENV" | grep -oP '(?<="COMMIT_ID": ")[^"]*')
          COMMIT_MESSAGE=$(echo "$GITHUB_ENV" | grep -oP '(?<="COMMIT_MESSAGE": ")[^"]*')
          AUTHOR=$(echo "$GITHUB_ENV" | grep -oP '(?<="AUTHOR": ")[^"]*')
          DATE=$(echo "$GITHUB_ENV" | grep -oP '(?<="DATE": ")[^"]*')
          CHANGED_FILES=$(echo "$GITHUB_ENV" | grep -oP '(?<="CHANGED_FILES": ")[^"]*')
          BRANCH_NAME=$(echo "$GITHUB_ENV" | grep -oP '(?<="BRANCH_NAME": ")[^"]*')
          BRANCH_DESCRIPTION=$(echo "$GITHUB_ENV" | grep -oP '(?<="BRANCH_DESCRIPTION": ")[^"]*')

          # Almacenamos la información en variables de GitHub Actions
          echo "COMMIT_ID: $COMMIT_ID" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE: $COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "AUTHOR: $AUTHOR" >> $GITHUB_ENV
          echo "DATE: $DATE" >> $GITHUB_ENV
          echo "CHANGED_FILES: $CHANGED_FILES" >> $GITHUB_ENV
          echo "BRANCH_NAME: $BRANCH_NAME" >> $GITHUB_ENV
          echo "BRANCH_DESCRIPTION: $BRANCH_DESCRIPTION" >> $GITHUB_ENV