name: Wats0n

on:
  push:
    branches:
      - 'feature/**'
      - 'feature'

permissions:
  contents: read
  actions: write

jobs:
  watson-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Info about Commit
        id: set-commit-info
        # Set the branch name and team name and file implicit in commit and save it in the environment variable
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          TEAM_NAME=${BRANCH_NAME#feature/}
          USER_NAME=$(git log -1 --pretty=format:'%an')
          USER_EMAIL=$(git log -1 --pretty=format:'%ae')
          # Save the branch name and team name in the environment variable to use it ${{ env.VARIABLE_NAME}}
          echo "TEAM_NAME=$TEAM_NAME" >> $GITHUB_ENV 
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "USER_NAME=$USER_NAME" >> $GITHUB_ENV
          echo "USER_EMAIL=$USER_EMAIL" >> $GITHUB_ENV
          echo "DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          # Save all the changed files in the environment variable to use it change-files-0000000000000.txt
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed-files-${{ env.DATETIME}}.txt
          git log ${{ github.event.before }}..${{ github.sha }} --pretty=format:"%H %s" > commit-messages-${{ env.DATETIME}}.txt

      - name: Exist changes in files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          declare -A workflows=( 
            ["templates/*.md"]="lintemplates.yaml"
            ["docs/*.md"]="lint.yaml"
            [".github/workflows/*.yaml"]="check.yaml"
            ["bin/*.py"]="checkpy.yaml"
          )
          declare -A found
          while IFS= read -r file; do
            for pattern in "${!workflows[@]}"; do
              if [[ "$file" == $pattern ]]; then
                found["$pattern"]=true
              fi
            done
          done < changed-files-${{ env.DATETIME}}.txt

          for pattern in "${!found[@]}"; do
            echo "Triggering ${workflows[$pattern]} workflow..."
            gh workflow run "${workflows[$pattern]}" --ref feature
          done

      - name: Run on success
        if: success()
        run: |
          echo "The complete information on this execution is:" >> resumen-watson-${{ env.DATETIME}}.txt
          echo "${{ env.TEAM_NAME}} has requested to perform $GITHUB_EVENT_NAME." >> resumen-watson-${{ env.DATETIME}}.txt
          echo "with the following content:" >> resumen-watson-${{ env.DATETIME}}.txt
          echo "Commit:" >> resumen-watson-${{ env.DATETIME}}.txt
          cat commit-messages-${{ env.DATETIME}}.txt >> resumen-watson-${{ env.DATETIME}}.txt
          echo "Files:" >> resumen-watson-${{ env.DATETIME}}.txt
          cat changed-files-${{ env.DATETIME}}.txt >> resumen-watson-${{ env.DATETIME}}.txt
          echo "and the result has been successful." >> resumen-watson-${{ env.DATETIME}}.txt

      - name: Run on failure
        if: failure()
        run: 
          echo "The complete information on this execution is:" >> resumen-watson-${{ env.DATETIME}}.txt
          echo "${{ env.TEAM_NAME}} has requested to perform $GITHUB_EVENT_NAME." >> resumen-watson-${{ env.DATETIME}}.txt
          echo "with the following content:" >> resumen-watson-${{ env.DATETIME}}.txt
          echo "Commit:" >> resumen-watson-${{ env.DATETIME}}.txt
          cat commit-messages-${{ env.DATETIME}}.txt >> resumen-watson-${{ env.DATETIME}}.txt
          echo "Files:" >> resumen-watson-${{ env.DATETIME}}.txt
          cat changed-files-${{ env.DATETIME}}.txt >> resumen-watson-${{ env.DATETIME}}.txt
          echo "and the result has not been successful." >> resumen-watson-${{ env.DATETIME}}.txt

      - name: Upload success file
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: success-files
          path: |
            changed-files-${{ env.DATETIME}}.txt
            commit-messages-${{ env.DATETIME}}.txt

      - name: Upload failure file
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-files
          path: |
            changed-files-${{ env.DATETIME}}.txt
            commit-messages-${{ env.DATETIME}}.txt