name: Ka0s

on:
  push:
    branches:
      - 'main'
      - 'release/new'
      - 'feature'
      - 'hotfix'

permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write

jobs:
  watson-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
      # Checkout the repository to get the information of the commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_TOKEN }}

      - name: Set Info about Commit
        id: set-commit-info
        # Set the branch name and team name and file implicit in commit and save it in the environment variable
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          USER_NAME=$(git log -1 --pretty=format:'%an')
          USER_EMAIL=$(git log -1 --pretty=format:'%ae')
          PATH_RESUME="./core/results/"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "USER_NAME=$USER_NAME" >> $GITHUB_ENV
          echo "USER_EMAIL=$USER_EMAIL" >> $GITHUB_ENV
          echo "PATH_RESUME=$PATH_RESUME" >> $GITHUB_ENV
          echo "DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          git config --global user.name ${{ secrets.KAOS_USER_NAME }}
          git config --global user.email ${{ secrets.KAOS_USER_EMAIL }}

      - name: Generate files report
        id: generate-files-report
        run: |
          # Crear un fichero de resumen con todos los datos de los commits asociados, esta información es usada en todo el clico de vida del workflow
          # en cada paso este fichero actualiza el contenido, dado que el workflow deja registro en tres partes distintas
          git log ${{ github.event.before }}..${{ github.sha }} --pretty=format:'%H%n%an%n%ae%n%ad%n%s' > ${{ env.PATH_RESUME }}commit-summary-${{ env.DATETIME }}.txt
          echo "Commit Summary:"
          cat ${{ env.PATH_RESUME }}commit-summary-${{ env.DATETIME }}.txt
          # Crear un fichero con la ruta completa y el nombre ficheros implicados en el commit
          # este paso es el que provoca que el workflow siga un camino u otro
          git diff-tree --no-commit-id --name-only -r $(git log -1 --pretty=format:'%H') > ${{ env.PATH_RESUME }}files-in-commit-${{ env.DATETIME }}.txt
          echo "Files in Commit:"
          cat ${{ env.PATH_RESUME }}commit-summary-${{ env.DATETIME }}.txt
          cat ${{ env.KAOS_CORE_MODULES }}
          cat ${{ env.KAOS_CORE_FILES }}
          # Acceder al secreto
          WORKFLOWS_JSON=${{ secrets.KAOS_CORE_MODULES }}
          
          # Convertir el JSON de nuevo a un array asociativo
          declare -A workflows=$(echo "$WORKFLOWS_JSON" | jq -r 'to_entries | map("\(.key)=\(.value)") | .[]')
          
          # Imprimir el contenido del array asociativo
          for key in "${!workflows[@]}"; do
            echo "$key: ${workflows[$key]}"
          done


      - name: Upload parameter file
        uses: actions/upload-artifact@v4
        with:
          name: reports-files
          path: |
            ${{ env.PATH_RESUME }}commit-summary-${{ env.DATETIME }}.txt
            ${{ env.PATH_RESUME }}files-in-commit-${{ env.DATETIME }}.txt
