name: Init Ka0S

on:
  push:
    branches:
      - 'feature/**'
      - 'feature'

permissions:
  contents: read
  actions: write

jobs:
  initprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Team Name
        id: set-branch-name
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          CLEAN_BRANCH_NAME=${BRANCH_NAME#feature/}
          echo "CLEAN_BRANCH_NAME=$CLEAN_BRANCH_NAME" >> $GITHUB_ENV

      - name: Identify User of the Team
        id: identify-user
        run: |
          user=$(git log -1 --pretty=format:'%an')
          echo "user=$user" >> $GITHUB_ENV

      - name: Display User Name and Team Name
        run: echo "Push has been performed by the user ${{ env.user }} of the Team ${{ env.CLEAN_BRANCH_NAME }}"

      - name: Identify Changed Files
        id: changed-files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed-files.txt
          cat changed-files.txt

          - name: Exist changes in files
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            declare -A workflows=(
              ["templates/*.md"]="lintemplates.yaml"
              ["docs/*.md"]="lint.yaml"
              [".github/workflows/*.yaml"]="check.yaml"
              ["bin/*.py"]="checkpy.yaml"
            )
        
            declare -A found
        
            while IFS= read -r file; do
              for pattern in "${!workflows[@]}"; do
                if [[ "$file" == $pattern ]]; then
                  found["$pattern"]=true
                fi
              done
            done < changed-files.txt
        
            for pattern in "${!found[@]}"; do
              echo "Triggering ${workflows[$pattern]} workflow..."
              gh workflow run "${workflows[$pattern]}" --ref feature
            done