name: Ka0s Init

on:
  workflow_dispatch:
    inputs:
      kaos-issue-id:
        description: 'Issue ID'
        default: ""
        required: true
      kaos-involved-file:
        description: 'Involved Files to process'
        default: ""
        required: true

permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write

env:
  KAOS_MODULE: "[Ka0S] INIT"
  GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
  
jobs:
  kaos-init-process:
    runs-on: 
      group: kaos-init
    env:
      GH_TOKEN: ${{ secrets.KAOS_TOKEN }} 
      BRANCH_NAME: ${{ github.ref }}
      USER_NAME: ${{ github.actor.name}}
      USER_EMAIL: ${{ github.actor.email }}
      PATH_RESUME: "core/results/"
    steps:
      - id: repo # Check out the repository to get information of the commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_TOKEN }}

      - id: module
        env:
            modules: ${{ secrets.KAOS_CORE_MODULES }}
            files: ${{ secrets.KAOS_CORE_FILES }}
        run: |
          # Vamos a determinar que accion debera de ser la siguiente en el flujo
          IFS=',' read -r -a module_array <<< "$modules"
          echo "Estos son todos los modulos: $modules "
          while IFS= read -r line; do
            echo "Este es el fichero $line de la lista ${{ github.event.inputs.kaos-involved-file }}"
            for module in "${module_array[@]}"; do
              echo "El modulo es $module"
              echo "Y el fichero es $line"
              if [[ "$line" == *"$module"* ]]; then
                file_name=$(basename "$line")
                file_extension="${file_name##*.}"
                echo "Encontrado el módulo: $module"
                echo "Nombre del fichero: $file_name"
                echo "Extensión del fichero: $file_extension"
                echo "FILE_NAME=$file_name" >> $GITHUB_ENV
                echo "FILE_EXTENSION=$file_extension" >> $GITHUB_ENV
                IFS=',' read -r -a file_array <<< "$files"
                echo "Este es el valor de la variable KAOS_CORE_FILES:$files"
                  for file in "${file_array[@]}"; do
                  echo "Extensión del fichero: $file_extension"
                  echo "Extensión del sistema: $file"
                  workflow=$file_extension"lint.yaml"
                    if [[ "$file_extension" == "$file" ]]; then
                      # en este caso deberemos de genarar una issue indicando de una acción en ejecucion y el máximo detalle
                      KAOS_ISSUE_TITLE="[WORFLOW] Action Started: ${{ github.workflow }}"
                      KAOS_ISSUE_BODY=$(printf "This is a issue created by ${{ env.KAOS_MODULE }} to register Actions workflows **${{ github.workflow }}**.\nIt has been requested by: **${{ github.actor }}**\n\n**Message:**\n\`\`\`\nPlease check the job logs for ${{ secrets.KAOS_ACTIONS_URL }}${{ github.run_id }}\n**Please check the issues for more details**\n\`\`\`\n\n**Workflow Name:** ${{ github.workflow }}\n**Job Name:** ${{ github.job }}\n**Run ID:** ${{ github.run_id }}\n**Run Number:** ${{ github.run_number }}\n**Repository:** ${{ github.repository }}\n**Branch:** ${{ github.ref }}\n**Commit:** ${{ github.sha }}\n\n**Files Involved:**\n${{ env.INVOLVED }}\n")
                      gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-body="$KAOS_ISSUE_BODY" -f kaos-issue-id=${{ github.event.inputs.kaos-issue-id }} -f kaos-issue-actions=comment
                      # Lanzamos el lint del fichero
                      gh workflow run $workflow --ref ${{ github.ref }} -f kaos-origin=${{ github.run_id }} -f kaos-files=$line -f kaos-issue-id=${{ github.event.inputs.kaos-issue-id }}
                      gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-title=$KAOS_ISSUE_TITLE -f kaos-issue-body="Launch workflow $workflow" -f kaos-issue-id=${{ github.event.inputs.kaos-issue-id }}
                    else
                      #Si el fichero que se esta intentando subir no esta permitido se abre una issue indicando el error.
                      echo "Error el fichero que intenta subir no esta permitido"
                    fi
                  done
              else
                echo "No ha ejecuciones para este módulo: $module"
                echo "Not execution module $module does not exist in changed in files envolved"
                  # en este caso deberemos de genarar una issue indicando de una acción no permitida y el máximo detalle
                  KAOS_ISSUE_TITLE="${{ env.KAOS_MODULE }} Action Failed: ${{ github.workflow }}"
                  KAOS_ISSUE_BODY=$(printf "This is a resume to the ${{ env.KAOS_MODULE }} Action workflow **${{ github.workflow }}**.\nIt has been requested by: **${{ github.actor }}**\n\n**Success Message:**\n\`\`\`\nPlease check the job logs for ${{ secrets.KAOS_ACTIONS_URL }}${{ github.run_id }}\n**Please check the issues for more details**\n\`\`\`\n\n**Workflow Name:** ${{ github.workflow }}\n**Job Name:** ${{ github.job }}\n**Run ID:** ${{ github.run_id }}\n**Run Number:** ${{ github.run_number }}\n**Repository:** ${{ github.repository }}\n**Branch:** ${{ github.ref }}\n**Commit:** ${{ github.sha }}\n\n**Files Involved:**\n${{ env.INVOLVED }}\n")
              fi
            done
          done < ${{ github.event.inputs.kaos-involved-file }}
      
  handle_failure:
    runs-on: 
      group: kaos-init
    needs: [kaos-init-process]
    if: ${{ failure() }}
    steps:
      - id: check-execution
        env:
          GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
        run: |
          echo "Error detected in ${{ env.KAOS_MODULE }}, creating issue..."
          KAOS_ISSUE_TITLE="${{ env.KAOS_MODULE }} Action Failed: ${{ github.workflow }}"
          KAOS_ISSUE_BODY=$(cat <<'EOF'
          An error occurred in the ${{ env.KAOS_MODULE }} Action workflow **${{ github.workflow }}**.
          **${{ env.KAOS_MODULE }}  Message:**
          El error ha sido en : ${{  github.run_id }}
          ejecute este comando en su consola y podrá consultar el fallo del trabajo
          gh run view ${{  github.run_id }} --log-failed
          \`\`\`
          **Please check the job logs for ${{ secrets.KAOS_ACTIONS_URL }}${{ github.run_id }}**
          \`\`\`
          **Workflow Name:** ${{ github.workflow }}
          **Job Name:** ${{ github.job }}
          **Run ID:** ${{ github.run_id }}
          **Run Number:** ${{ github.run_number }}
          **Repository:** ${{ github.repository }}
          **Branch:** ${{ github.ref }}
          **Commit:** ${{ github.sha }}
          Please investigate the issue.
          EOF
          )
          gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-title="$KAOS_ISSUE_TITLE" -f kaos-issue-body="$KAOS_ISSUE_BODY" -f kaos-issue-actions=create -f kaos-issue-tag="bug"   
