name: Ka0s Issues

on:
  workflow_dispatch: # Permite disparar el workflow manualmente
    inputs:
      kaos-issue-title:
        description: 'Title'
        default: "Kaos Issue Title Example"
        required: true
      kaos-issue-body:
        description: 'Body'
        default: "Kaos Issue Body Example"
        required: true
      kaos-issue-body-file:
        description: 'Attach file to body'
        default: ""
        required: false
      kaos-issue-actions:
        description: 'Issue Actions'
        default: "comment"
        required: false
        type: choice
        options:
        - create
        - comment
        - close
        - reopen
      kaos-issue-tag:
        description: 'Issue tag'
        default: "bug"
        required: false
      kaos-issue-id:
        description: 'Issue ID'
        default: "1"
        required: true
  
permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write

jobs:
  kaos-init-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
      # Checkout the repository to get the information of the commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_TOKEN }}

      - name: Set Info about Commit temp vars
        # Set the branch name and team name and file implicit in commit and save it in the environment variable
        run: |
          BRANCH_NAME=${{ github.event.base_ref }}
          USER_NAME=${{ github.actor.name}}
          USER_EMAIL=${{ github.actor.email }}
          PATH_RESUME="core/results/"
          KAOS_MODULE="[ISSUE]"
          KAOS_STEP_MODULE=""
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "USER_NAME=$USER_NAME" >> $GITHUB_ENV
          echo "USER_EMAIL=$USER_EMAIL" >> $GITHUB_ENV
          echo "PATH_RESUME=$PATH_RESUME" >> $GITHUB_ENV
          echo "KAOS_MODULE=$KAOS_MODULE" >> $GITHUB_ENV
          echo "KAOS_STEP_MODULE=$KAOS__STEP_MODULE" >> $GITHUB_ENV
          echo "DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      
      - name: Work with issues
        env:
          GH_TOKEN: ${{ secrets.GH_APP_TEC }}
        run: |
            # Lo primero comprobar la acción que queremos realizar
            case ${{ github.event.inputs.kaos-issue-actions }} in
                create)
                    # Abrimos la petición y pasamos el issue ID a la variable de repositorio KAOS_ISSUE_ID
                    gh issue create -t "${{ github.event.inputs.kaos-issue-title }}" -b "${{ github.event.inputs.kaos-issue-body }}" -l "${{ github.event.inputs.kaos-issue-tag }}" -a "${{ github.actor.name }}"
                    ;;
                comment)
                    # Añadimos comentarios a una issue en concreto o ficheros
                    if [[ "${{ github.event.inputs.kaos-issue-body-file }}" == ""]]
                      gh issue comment ${{ github.event.inputs.kaos-issue-id }} -b "${{ github.event.inputs.kaos-issue-body }}"
                    else
                      gh issue comment ${{ github.event.inputs.kaos-issue-id }} -b "${{ github.event.inputs.kaos-issue-body }}" --body-file ${{ github.event.inputs.kaos-issue-body-file }}
                    fi
                  ;;
                close)
                    # Cerramos una issue finalizada
                    gh issue close ${{ github.event.inputs.kaos-issue-id }} -c "Issue: ${{ github.event.inputs.kaos-issue-id }} closed by  ${{ github.actor.name }}" -r "completed"
                  ;;
                reopen)
                    # Reabrimos una issue que no ha sido solucionada
                    title="${{ github.event.inputs.kaos-issue-title }}"
                    if [[ "$title" == *"[SUCCESS]"* ]]; then
                      echo "Found [SUCCESS] in the title"
                      new_title="${title//[SUCCESS]/[FAILED]}"
                      echo "new_title=$new_title" >> $GITHUB_ENV
                    fi
                    gh issue reopen ${{ github.event.inputs.kaos-issue-id }} -c "Reopen Issue: ${{ github.event.inputs.kaos-issue-id }} by  ${{ github.actor.name }}"
                    gh issue edit ${{ github.event.inputs.kaos-issue-id }} -t "$new_title"
                    gh issue edit ${{ github.event.inputs.kaos-issue-id }} --remove-label "resolved"
                  ;;
                *)
                    # Si no es alguna de las anteriores
                    # el modulo de issues fallara y creara una issue propia  
                  ;;
            esac

      - name: Check execution
        env:
          GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
        if: failure()
        run: |
          echo "Error detected in KaoS INIT, creating issue..."
          KAOS_ISSUE_TITLE="${{ env.KAOS_MODULE }} Action Failed: ${{ github.workflow }}"
          KAOS_ISSUE_BODY=$(cat <<'EOF'
          An error occurred in the ${{ env.KAOS_MODULE }} Action workflow **${{ github.workflow }}**.
          **[KAOS INIT]  Message:**
          \`\`\`
          **Please check the job logs for ${{ secrets.KAOS_ACTIONS_URL }}${{ github.run_id }}**
          \`\`\`
          **Workflow Name:** ${{ github.workflow }}
          **Job Name:** ${{ github.job }}
          **Run ID:** ${{ github.run_id }}
          **Run Number:** ${{ github.run_number }}
          **Repository:** ${{ github.repository }}
          **Branch:** ${{ github.ref }}
          **Commit:** ${{ github.sha }}
          **Files Involved:**
          ${{ env.INVOLVED }}
          Please investigate the issue.
          EOF
          )
          gh issue create --title "$KAOS_ISSUE_TITLE" --body "$KAOS_ISSUE_BODY" --label "bug,core" --repo ${{ github.repository }}

            