# This is a basic workflow to help you get started with Actions
name: Ka0S
# Controls when the workflow will run
on:
  push: 
    branches-ignore:
      - 'main'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Primer Job dentro del Job
  job-core:
    # Condicion antes de comenzar el jobs
    if: ${{ always() }} 
    outputs:
      RNBRANCH: ${{ steps.core.outputs.RNBRANCH }}
      RNNUMBER: ${{ steps.core.outputs.RNNUMBER }}
    runs-on: 
      group: kaos-test
    permissions:
      contents: write
      actions: write
      issues: write
      pull-requests: write

    steps:
      - id: repo
        if: ${{ always() }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_TOKEN }}
          
      - id: core
      # vamos a capturar toda la información del evento que dispara el actions para controlar el flujo que debera de seguir
        if: ${{ always() }}
        env:
          RNBRANCH: "coño"
          RNNUMBER: "polla"
        run: |
          echo "Branch name is ${{ github.ref }}"
          case "${{ github.ref }}" in
            *RN[0-9]*-*)
              rn=$(echo "${{ github.ref }}" | grep -o 'RN[0-9]*')
              ;;
            *F[0-9]*-*)
              rn=$(echo "${{ github.ref }}" | grep -o 'F[0-9]*')
              ;;
            *H[0-9]*-*)
              rn=$(echo "${{ github.ref }}" | grep -o 'H[0-9]*')
              ;;
            *E[0-9]*-*)
              rn=$(echo "${{ github.ref }}" | grep -o 'H[0-9]*')
              ;;
            *)
              echo "No debería de estar haciendo esto"
              exit 1
              ;;
          esac
          RNBRANCH=$(echo "$rn" | grep -o '^[A-Za-z]*')
          RNNUMBER=$(echo "$rn" | grep -o '[0-9]*')
          echo "Extracted RN Branch: $RNBRANCH"
          echo "Extracted RN Number: $RNNUMBER"
          echo "env.RNBRANCH=$RNBRANCH" >> $GITHUB_ENV
          echo "RNBRANCH=$RNBRANCH" >> $GITHUB_OUTPUT
          echo "RNNUMBER=$RNNUMBER" >> $GITHUB_ENV   
          echo "Commit SHA is ${{ github.sha }}"
          echo "Repo origin is ${{ github.repository }}"
          echo "Launch by ${{ github.actor }}"
          echo "${{ env.RNBRANCH}}"
          echo "${{ env.RNNUMBER}}"

  job-flows:
    needs: job-core # Si antes haber evaluado la información no ejecutamos nada
    runs-on:
      group: kaos-test
    permissions:
      contents: write
      actions: write
      issues: write
      pull-requests: write
    steps:
      - id: release-new-flow
        if: ${{ needs.job-core.outputs.RNBRANCH == 'RN' }}
        run: |
          echo "release-new-flow"
          echo "Branch name is ${{ github.ref }}"
          echo "Commit SHA is ${{ github.sha }}"
          echo "Repo origin is ${{ github.repository }}"
          echo "Launch by ${{ github.actor }}"
      - id: feature-flow
        if: ${{ needs.job-core.outputs.RNBRANCH == 'F' }}
        run: |
          echo "feature-flow"
          echo "Branch name is ${{ github.ref }}"
          echo "Commit SHA is ${{ github.sha }}"
          echo "Repo origin is ${{ github.repository }}"
          echo "Launch by ${{ github.actor }}"
      - id: hotfix-flow
        if: ${{ needs.job-core.outputs.RNBRANCH == 'H' }}
        run: |
          echo "hotfix-flow"
          echo "Branch name is ${{ github.ref }}"
          echo "Commit SHA is ${{ github.sha }}"
          echo "Repo origin is ${{ github.repository }}"
          echo "Launch by ${{ github.actor }}"
      - id: execution-flow
        if: ${{ needs.job-core.outputs.RNBRANCH == 'E' }}
        run: |
          execution-flow
          echo "Branch name is ${{ github.ref }}"
          echo "Commit SHA is ${{ github.sha }}"
          echo "Repo origin is ${{ github.repository }}"
          echo "Launch by ${{ github.actor }}"


