# This is a basic workflow to help you get started with Actions
name: Ka0S
# Controls when the workflow will run
on:
  push: 
    paths:
      - '**.yaml'
    branches-ignore:
      - 'H*'
      - 'F*'
      - 'RN*'
      
env:
  KAOS_MODULE: "[Ka0S]"
  PATH_RESUME: "core/results/"
  GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Worflow
  job-core:
    # Condicion antes de comenzar el jobs
    if: ${{ !contains(github.event.head_commit.message, '[Ka0S] ') }} 
    outputs:
      KAOS_BRANCH: ${{ steps.core.outputs.RNBRANCH }}
      KAOS_NUMBER: ${{ steps.core.outputs.RNNUMBER }}
      KAOS_INVOLVED: ${{ steps.files.outputs.INVOLVED }}
    runs-on: 
      group: kaos-test
    permissions:
      contents: write
      actions: write
      issues: write
      pull-requests: write
    env:
      KAOS_PATH_RESUME: "core/results/"
      KAOS_STEP_MODULE: ""
      KAOS_CODE: ""
    steps:
      - id: repo
        if: ${{ always() }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_TOKEN }}
          
          
      - id: core
      # vamos a capturar toda la información del evento que dispara el action para controlar el flujo que debera de seguir
        if: ${{ !contains(github.event.head_commit.message, '[Ka0S] ') }}
        run: |
          # Comprobamos el flow que deberemos de ejecutar
          echo "Branch name is ${{ github.ref }}"
          case "${{ github.ref }}" in
            *RN[0-9]*-*)
              rn=$(echo "${{ github.ref }}" | grep -o 'RN[0-9]*')
              ;;
            *F[0-9]*-*)
              rn=$(echo "${{ github.ref }}" | grep -o 'F[0-9]*')
              ;;
            *H[0-9]*-*)
              rn=$(echo "${{ github.ref }}" | grep -o 'H[0-9]*')
              ;;
            *E[0-9]*-*)
              rn=$(echo "${{ github.ref }}" | grep -o 'H[0-9]*')
              ;;
            *)
              echo "No debería de estar haciendo esto"
              exit 1
              ;;
          esac
          RNBRANCH=$(echo "$rn" | grep -o '^[A-Za-z]*')
          RNNUMBER=$(echo "$rn" | grep -o '[0-9]*')
          echo "Extracted RN Branch: $RNBRANCH"
          echo "Extracted RN Number: $RNNUMBER"
          echo "KAOS_CODE=$(echo "$rn" | grep -o '^[A-Za-z]*')-$(echo "$rn" | grep -o '[0-9]*')" >> $GITHUB_ENV
          echo "La variable de KAOS_CODE es $KAOS_CODE"
          echo "La variable de KAOS_CODE es ${{ env.KAOS_CODE }}"
          echo "RNBRANCH=$RNBRANCH" >> $GITHUB_OUTPUT
          echo "RNNUMBER=$RNNUMBER" >> $GITHUB_OUTPUT   
          echo "Commit SHA is ${{ github.sha }}"
          echo "Repo origin is ${{ github.repository }}"
          echo "Launch by ${{ github.actor }}"
          BRANCH_NAME=${{ github.event.base_ref }}

      - id: files
        env:
          USER_NAME: ${{ secrets.KAOS_USER_NAME }}
          USER_EMAIL: ${{ secrets.KAOS_USER_EMAIL }}
        if: ${{ always() }}
        run: |
          # Crear un fichero de resumen con todos los datos de los commits asociados, esta información es usada en todo el ciclo de vida del workflow
          git log ${{ github.event.before }}..${{ github.sha }} --pretty=format:'%H%n%an%n%ae%n%ad%n%s' > ${{ env.KAOS_PATH_RESUME }}commit-summary-${{ env.KAOS_CODE }}.txt
          # Crear un fichero con la ruta completa y el nombre ficheros implicados en el commit
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > ${{ env.KAOS_PATH_RESUME }}files-in-commit-${{ env.KAOS_CODE }}.txt
          INVOLVED=${{ env.KAOS_PATH_RESUME }}files-in-commit-${{ env.KAOS_CODE }}.txt
          echo "INVOLVED=$INVOLVED" >> $GITHUB_OUTPUT
          git config --global user.name "${{ env.USER_NAME }}"
          git config --global user.email "${{ env.USER_EMAIL}}"
          git pull
          git add ${{ env.KAOS_PATH_RESUME }}*
          git commit -m "[Ka0S] se generan los ficheros commit-summary files-in-commit"
          git push

  job-flows:
    needs: job-core # Si antes haber evaluado la información not∫ ejecutamos nada
    outputs:
      KAOS_BODY_ISSUE: ${{ steps.release-new-flow.outputs.SUMMARY }}
    runs-on:
      group: kaos-test
    permissions:
      contents: write
      actions: write
      issues: write
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
      SUMMARY: ""
      BRANCH_ACTION: ${{ needs.job-core.outputs.KAOS_BRANCH }}
      BRANCH_NUMBER: ${{ needs.job-core.outputs.KAOS_NUMBER }}
      BRANCH_INVOLVED: ${{ needs.job-core.outputs.KAOS_INVOLVED }}
    steps:
      - id: release-new-flow
        if: ${{ needs.job-core.outputs.KAOS_BRANCH == 'RN' }}
        run: |
          echo "RN - Este es el fichero implicado ${{ needs.job-core.outputs.KAOS_INVOLVED }}"
          KAOS_ISSUE_TITLE="[Ka0S] Job:${{ github.workflow }} action"
          KAOS_ISSUE_BODY=$(printf "${{ github.workflow }} has been initiated by ${{ github.triggering_actor }}.\n${{ github.action_status }} launch by ${{ github.actor }}\nBranch name is ${{ github.ref }}\nCommit SHA is ${{ github.sha }}\nRepo origin is ${{ github.repository }}\nAssigned number issue ${{ env.BRANCH_NUMBER }}\nExecuted flow about ${{ env.BRANCH_ACTION }}\n**Please check the job logs for ${{ secrets.KAOS_ACTIONS_URL }}${{ github.run_id }}**\n**Workflow Name:** ${{ github.workflow }}\n**Job Name:** ${{ github.job }}\n**Run ID:** ${{ github.run_id }}\n**Run Number:** ${{ github.run_number }}\n**Repository:** ${{ github.repository }}\n**Branch:** ${{ github.ref }}\n**Commit:** ${{ github.sha }}\n**Actions Involved:**\n**Ref Flow: ${{ env.BRANCH_ACTION }}**\n**Ref Issue: ${{ env.BRANCH_NUMBER }}**\n**Please review issue ${{ env.BRANCH_NUMBER }} for more information.**\n")
          gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-body="$KAOS_ISSUE_BODY"  -f kaos-issue-id=${{ env.BRANCH_NUMBER }} -f kaos-issue-actions=comment -f kaos-issue-body-file=${{ env.BRANCH_INVOLVED }}
          gh workflow run init.yaml  --ref ${{ github.ref }} -f kaos-issue-id=${{ env.BRANCH_NUMBER }} -f kaos-involved-file=${{ env.BRANCH_INVOLVED }}
          KAOS_ISSUE_BODY="Now initiates flow process to check ${{ env.BRANCH_ACTION }}-${{ env.BRANCH_NUMBER }} Ka0S_Code"
          gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-body="$KAOS_ISSUE_BODY"  -f kaos-issue-id=${{ env.BRANCH_NUMBER }} -f kaos-issue-actions=comment -f kaos-issue-body-file=${{ env.BRANCH_INVOLVED }}   
      - id: feature-flow
        if: ${{ needs.job-core.outputs.KAOS_BRANCH == 'F' }}
        run: |
          echo "F - Este es el fichero implicado ${{ needs.job-core.outputs.KAOS_INVOLVED }}"
          KAOS_ISSUE_TITLE="[Ka0S] Job:${{ github.workflow }} action"
          KAOS_ISSUE_BODY=$(printf "${{ github.workflow }} has been initiated by ${{ github.triggering_actor }}.\n${{ github.action_status }} launch by ${{ github.actor }}\nBranch name is ${{ github.ref }}\nCommit SHA is ${{ github.sha }}\nRepo origin is ${{ github.repository }}\nAssigned number issue ${{ env.BRANCH_NUMBER }}\nExecuted flow about ${{ env.BRANCH_ACTION }}\n**Please check the job logs for ${{ secrets.KAOS_ACTIONS_URL }}${{ github.run_id }}**\n**Workflow Name:** ${{ github.workflow }}\n**Job Name:** ${{ github.job }}\n**Run ID:** ${{ github.run_id }}\n**Run Number:** ${{ github.run_number }}\n**Repository:** ${{ github.repository }}\n**Branch:** ${{ github.ref }}\n**Commit:** ${{ github.sha }}\n**Actions Involved:**\n**Ref Flow: ${{ env.BRANCH_ACTION }}**\n**Ref Issue: ${{ env.BRANCH_NUMBER }}**\n**Please review issue ${{ env.BRANCH_NUMBER }} for more information.**\n")
          gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-body="$KAOS_ISSUE_BODY"  -f kaos-issue-id=${{ env.BRANCH_NUMBER }} -f kaos-issue-actions=comment -f kaos-issue-body-file=${{ env.BRANCH_INVOLVED }}
          gh workflow run init.yaml  --ref ${{ github.ref }} -f kaos-issue-id=${{ env.BRANCH_NUMBER }} -f kaos-involved-file=${{ env.BRANCH_INVOLVED }}
          KAOS_ISSUE_BODY="Now initiates flow process to check ${{ env.BRANCH_ACTION }}-${{ env.BRANCH_NUMBER }} Ka0S_Code"
          gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-body="$KAOS_ISSUE_BODY"  -f kaos-issue-id=${{ env.BRANCH_NUMBER }} -f kaos-issue-actions=comment -f kaos-issue-body-file=${{ env.BRANCH_INVOLVED }}
      - id: hotfix-flow
        if: ${{ needs.job-core.outputs.KAOS_BRANCH == 'H' }}
        run: |
          echo "H - Este es el fichero implicado ${{ needs.job-core.outputs.KAOS_INVOLVED }}"
          KAOS_ISSUE_TITLE="[Ka0S] Job:${{ github.workflow }} action"
          KAOS_ISSUE_BODY=$(printf "${{ github.workflow }} has been initiated by ${{ github.triggering_actor }}.\n${{ github.action_status }} launch by ${{ github.actor }}\nBranch name is ${{ github.ref }}\nCommit SHA is ${{ github.sha }}\nRepo origin is ${{ github.repository }}\nAssigned number issue ${{ env.BRANCH_NUMBER }}\nExecuted flow about ${{ env.BRANCH_ACTION }}\n**Please check the job logs for ${{ secrets.KAOS_ACTIONS_URL }}${{ github.run_id }}**\n**Workflow Name:** ${{ github.workflow }}\n**Job Name:** ${{ github.job }}\n**Run ID:** ${{ github.run_id }}\n**Run Number:** ${{ github.run_number }}\n**Repository:** ${{ github.repository }}\n**Branch:** ${{ github.ref }}\n**Commit:** ${{ github.sha }}\n**Actions Involved:**\n**Ref Flow: ${{ env.BRANCH_ACTION }}**\n**Ref Issue: ${{ env.BRANCH_NUMBER }}**\n**Please review issue ${{ env.BRANCH_NUMBER }} for more information.**\n")
          gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-body="$KAOS_ISSUE_BODY"  -f kaos-issue-id=${{ env.BRANCH_NUMBER }} -f kaos-issue-actions=comment -f kaos-issue-body-file=${{ env.BRANCH_INVOLVED }}
          gh workflow run init.yaml  --ref ${{ github.ref }} -f kaos-issue-id=${{ env.BRANCH_NUMBER }} -f kaos-involved-file=${{ env.BRANCH_INVOLVED }}
          KAOS_ISSUE_BODY="Now initiates flow process to check ${{ env.BRANCH_ACTION }}-${{ env.BRANCH_NUMBER }} Ka0S_Code"
          gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-body="$KAOS_ISSUE_BODY"  -f kaos-issue-id=${{ env.BRANCH_NUMBER }} -f kaos-issue-actions=comment -f kaos-issue-body-file=${{ env.BRANCH_INVOLVED }}
      - id: execution-flow
        if: ${{ needs.job-core.outputs.KAOS_BRANCH == 'E' }}
        run: |
          execution-flow
          echo "Branch name is ${{ github.ref }}"
          echo "Commit SHA is ${{ github.sha }}"
          echo "Repo origin is ${{ github.repository }}"
          echo "Launch by ${{ github.actor }}"

  handle_failure:
    runs-on: 
      group: kaos-test
    needs: [job-core, job-flows]
    if: ${{ failure() }}
    steps:

      - id: check-execution
        env:
          GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
        run: |
          echo "Error detected in ${{ env.KAOS_MODULE }}, creating issue..."
          KAOS_ISSUE_TITLE="${{ env.KAOS_MODULE }} Action Failed: ${{ github.workflow }}"
          KAOS_ISSUE_BODY=$(cat <<'EOF'
          An error occurred in the ${{ env.KAOS_MODULE }} Action workflow **${{ github.workflow }}**.
          **${{ env.KAOS_MODULE }}  Message:**
          El error ha sido en : ${{  github.run_id }}
          ejecute este comando en su consola y podrá consultar el fallo del trabajo
          gh run view ${{  github.run_id }} --log-failed
          \`\`\`
          **Please check the job logs for ${{ secrets.KAOS_ACTIONS_URL }}${{ github.run_id }}**
          \`\`\`
          **Workflow Name:** ${{ github.workflow }}
          **Job Name:** ${{ github.job }}
          **Run ID:** ${{ github.run_id }}
          **Run Number:** ${{ github.run_number }}
          **Repository:** ${{ github.repository }}
          **Branch:** ${{ github.ref }}
          **Commit:** ${{ github.sha }}
          Please investigate the issue.
          EOF
          )
          gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-workflow-id=${{  github.run_id }} -f kaos-issue-title="$KAOS_ISSUE_TITLE" -f kaos-issue-body="$KAOS_ISSUE_BODY" -f kaos-issue-actions=create -f kaos-issue-tag="bug"   