# This is a basic workflow to help you get started with Actions
name: Ka0S
# Controls when the workflow will run
on:
  push: 
    branches-ignore:
      - 'main'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Primer Job dentro del Job
  job-core:
    # Condicion antes de comenzar el jobs
    if: ${{ always() }} 
    runs-on: 
      group: kaos-test
    permissions:
      contents: write
      actions: write
      issues: write
      pull-requests: write
    outputs:
      output-core: ${{ steps.core.outputs.test }}
      output-evaluated: ${{ steps.evaluated.outputs.kaos_result }}
    steps:
      - id: repo
        if: ${{ always() }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_TOKEN }}
          
      - id: core
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      # vamos a capturar la información que ha permitido disparar el evento
        if: ${{ always() }}
        run: |
          echo "Este el job JOB-CORE"
          echo "Este es el paso JOB-ID CORE dentro de Job JOB-CORE"
          # echo "$GITHUB_CONTEXT"
          echo "Branch name is ${{ github.ref }}"
          case "${{ github.ref }}" in
            *RN[0-9]*-*)
              rn=$(echo "$ref" | grep -o 'RN[0-9]*')
              ;;
            *F[0-9]*-*)
              rn=$(echo "$ref" | grep -o 'F[0-9]*')
              ;;
            *H[0-9]*-*)
              rn=$(echo "$ref" | grep -o 'H[0-9]*')
              ;;
            *)
              echo "No debería de estar haciendo esto"
              exit 1
              ;;
          esac
          rn_branch=$(echo "$rn" | grep -o '^[A-Za-z]*')
          rn_number=$(echo "$rn" | grep -o '[0-9]*')
          echo "Extracted RN Branch: $rn_branch"
          echo "Extracted RN Number: $rn_number"
          echo "Commit SHA is ${{ github.sha }}"
          echo "Repo origin is ${{ github.repository }}"
          echo "Launch by ${{ github.actor }}"

  job-customer:
    needs: job-core # Podemos hacer dependiente la ejecución en funcion de que un job termine [job1, job2]
    runs-on:
      group: kaos-test
    permissions:
      contents: write
      actions: write
      issues: write
      pull-requests: write
    steps:
      - id: init
        if: ${{ always() }}
        run: |
          echo "JOB-CUSTOMER"
          echo "JOB-ID INIT"
          echo "Branch name is ${{ github.ref }}"
          echo "Commit SHA is ${{ github.sha }}"
          echo "Repo origin is ${{ github.repository }}"
          echo "Launch by ${{ github.actor }}"
      - id: varios
        if: ${{ always() }}
        run: |
          echo "JOB-CUSTOMER"
          echo "JOB-ID VARIOS"
          echo "Branch name is ${{ github.ref }}"
          echo "Commit SHA is ${{ github.sha }}"
          echo "Repo origin is ${{ github.repository }}"
          echo "Launch by ${{ github.actor }}"


