# This is a basic workflow to help you get started with Actions
name: Ka0S
# Controls when the workflow will run
on:
  push: 
    branches-ignore:
      - 'main'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Primer Job dentro del Job
  job-core:
    # Condicion antes de comenzar el jobs
    if: ${{ always() }} 
    outputs:
      KAOS_BRANCH: ${{ steps.core.outputs.RNBRANCH }}
      KAOS_NUMBER: ${{ steps.core.outputs.RNNUMBER }}
    runs-on: 
      group: kaos-test
    permissions:
      contents: write
      actions: write
      issues: write
      pull-requests: write

    steps:
      - id: repo
        if: ${{ always() }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_TOKEN }}
          
      - id: core
      # vamos a capturar toda la información del evento que dispara el actions para controlar el flujo que debera de seguir
        if: ${{ always() }}
        run: |
          echo "Branch name is ${{ github.ref }}"
          case "${{ github.ref }}" in
            *RN[0-9]*-*)
              rn=$(echo "${{ github.ref }}" | grep -o 'RN[0-9]*')
              ;;
            *F[0-9]*-*)
              rn=$(echo "${{ github.ref }}" | grep -o 'F[0-9]*')
              ;;
            *H[0-9]*-*)
              rn=$(echo "${{ github.ref }}" | grep -o 'H[0-9]*')
              ;;
            *E[0-9]*-*)
              rn=$(echo "${{ github.ref }}" | grep -o 'H[0-9]*')
              ;;
            *)
              echo "No debería de estar haciendo esto"
              exit 1
              ;;
          esac
          RNBRANCH=$(echo "$rn" | grep -o '^[A-Za-z]*')
          RNNUMBER=$(echo "$rn" | grep -o '[0-9]*')
          echo "Extracted RN Branch: $RNBRANCH"
          echo "Extracted RN Number: $RNNUMBER"
          echo "RNBRANCH=$RNBRANCH" >> $GITHUB_OUTPUT
          echo "RNNUMBER=$RNNUMBER" >> $GITHUB_OUTPUT   
          echo "Commit SHA is ${{ github.sha }}"
          echo "Repo origin is ${{ github.repository }}"
          echo "Launch by ${{ github.actor }}"

  job-flows:
    needs: job-core # Si antes haber evaluado la información no ejecutamos nada
    outputs:
      KAOS_BODY_ISSUE: ${{ steps.release-new-flow.outputs.SUMMARY }}
    runs-on:
      group: kaos-test
    permissions:
      contents: write
      actions: write
      issues: write
      pull-requests: write
    steps:
      - id: release-new-flow
        env:
          SUMMARY: ""
          BRANCH_ACTION: ${{ needs.job-core.outputs.KAOS_BRANCH }}
          BRANCH_NUMBER: ${{ needs.job-core.outputs.KAOS_NUMBER }}
        if: ${{ needs.job-core.outputs.KAOS_BRANCH == 'RN' }}
        run: |
          echo "SUMMARY<<EOF" >> $GITHUB_ENV
          echo "SUMMARY="Job:${{ github.workflow }} has been initiated by ${{ github.triggering_actor}}"" >> $GITHUB_ENV
          echo "${{ github.action_status }} launch by ${{ github.actor }}" >> $GITHUB_ENV
          echo "Branch name is ${{ github.ref }}" >> $GITHUB_ENV
          echo "Commit SHA is ${{ github.sha }}" >> $GITHUB_ENV
          echo "Repo origin is ${{ github.repository }}" >> $GITHUB_ENV
          echo "Assigned number issue ${{ env.BRANCH_ACTION }}" >> $GITHUB_ENV
          echo "Executed flow about ${{ env.BRANCH_ACTION }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          cat ${{ env.SUMMARY }}
      - id: feature-flow
        if: ${{ needs.job-core.outputs.KAOS_BRANCH == 'F' }}
        run: |
          echo "feature-flow"
          echo "Branch name is ${{ github.ref }}"
          echo "Commit SHA is ${{ github.sha }}"
          echo "Repo origin is ${{ github.repository }}"
          echo "Launch by ${{ github.actor }}"
      - id: hotfix-flow
        if: ${{ needs.job-core.outputs.KAOS_BRANCH == 'H' }}
        run: |
          echo "hotfix-flow"
          echo "Branch name is ${{ github.ref }}"
          echo "Commit SHA is ${{ github.sha }}"
          echo "Repo origin is ${{ github.repository }}"
          echo "Launch by ${{ github.actor }}"
      - id: execution-flow
        if: ${{ needs.job-core.outputs.KAOS_BRANCH == 'E' }}
        run: |
          execution-flow
          echo "Branch name is ${{ github.ref }}"
          echo "Commit SHA is ${{ github.sha }}"
          echo "Repo origin is ${{ github.repository }}"
          echo "Launch by ${{ github.actor }}"


