name: Markdown Lint Workflow

on:
  workflow_dispatch:

jobs:
  lint-md:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Variables de Entorno
        id: variables-entorno
        run: |
          echo "datetime=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Mostramos la variable
        id: mostrar-variable
        run: |
          echo "La fecha y hora actual es ${{ env.datetime }}"
          
