name: Schemas

on:
  workflow_dispatch:
    branches:
      - feature

permissions:
  contents: write

jobs:
  generate-schemas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install jsonschema

      - name: Generate JSON Schemas
        run: |
          mkdir -p schemas
          for file in templates/*.md; do
            filename=$(basename "$file" .md)
            python bin/generate_schema.py "$file" "schemas/${filename}-schema-master-0.0.0.json"
          done

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull
          git add schemas/
          git commit -m "Fix: generated JSON schemas"
          git push origin feature
