name: Ka0s Splunk

on:
    workflow_dispatch:
     inputs:
      kaos-issue-body-file:
        description: 'Attach file to body'
        default: ""
        required: true
      kaos-issue-id:
        description: 'Actions ID'
        default: ""
        required: true

permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write

jobs:
  kaos-splunk:
    runs-on: kaos-runner-splunk

    steps:
      - name: Checkout Repository
      # Checkout the repository to get the information of the commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_TOKEN }}

      - name: Set Info about Commit temp vars
        # Set the branch name and team name and file implicit in commit and save it in the environment variable
        run: |
          BRANCH_NAME=${{ github.event.base_ref }}
          USER_NAME=${{ github.actor.name}}
          USER_EMAIL=${{ github.actor.email }}
          PATH_RESUME="./observability/data/github/"
          KAOS_MODULE="[CORE SPLUNK]"
          KAOS_STEP_MODULE=""
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "USER_NAME=$USER_NAME" >> $GITHUB_ENV
          echo "USER_EMAIL=$USER_EMAIL" >> $GITHUB_ENV
          echo "PATH_RESUME=$PATH_RESUME" >> $GITHUB_ENV
          echo "KAOS_MODULE=$KAOS_MODULE" >> $GITHUB_ENV
          echo "KAOS_STEP_MODULE=$KAOS_STEP_MODULE" >> $GITHUB_ENV
          echo "DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Send file to Splunk
        env:
           GH_TOKEN: ${{ secrets.KAOS_ISSUE_TOKEN }}
           GH_REPO: ${{ secrets.KAOS_REPO }}
           GH_SPLUNK_URL: ${{ secrets.KAOS_SPLUNK_URL }}
           GH_SPLUNK_URL_IDX: ${{ secrets.KAOS_SPLUNK_URL_IDX }}
           GH_SPLUNK_USER: ${{ secrets.KAOS_SPLUNK_USER }}
           GH_SPLUNK_PASSWORD: ${{ secrets.KAOS_SPLUNK_PASSWORD }}
        run: |
          # Check url
          curl -v -k -s -d "username=$GH_SPLUNK_USER&password=$GH_SPLUNK_PASSWORD" "${{ env.GH_SPLUNK_URL }}en-US/services/auth/login"
          # Autenticación
          index_name='idx_kaos_github'
          # Obtener la clave de sesión
          curl -k -s -d "username=${{ env.GH_SPLUNK_USER }}&password=${{ env.GH_SPLUNK_PASSWORD}}" "${{ env.GH_SPLUNK_URL }}en-US/services/auth/login"
          session_key=$(echo $response | sed -n 's:.*<sessionKey>\(.*\)</sessionKey>.*:\1:p')
          # Leer el contenido del fichero
          file_path='${{ github.event.inputs.kaos-issue-body-file }}'
          data=$(cat $file_path)

          # Enviar datos al índice específico
          # KAOS_RESPONSE_IDX=$(curl -k -s -H "Authorization: Splunk $session_key" -d "$data" "${{ env.GH_SPLUNK_URL_IDX }}en_US/services/receivers/simple")
          curl -k -u admin:splunk/splunk -X POST "https://80.28.162.237:8089/services/receivers/stream?sourcetype=st_kaos_github&index=idx_kaos_github&host=curl-testing" -H "Content-Type: multipart/form-data" -F "file=@${{ github.event.inputs.kaos-issue-body-file }}"
      
      - name: Check execution
        env:
          GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
          GH_ISSUE_ID: ${{ vars.KAOS_ISSUE_ID }}
        if: failure()
        run: |
          echo "Error detected in Ka0S SPLUNK, creating issue..."
          KAOS_ISSUE_TITLE="Ka0S SPLUNK Action Failed: ${{ github.workflow }}"
          KAOS_ISSUE_BODY=$(cat <<'EOF'
          An error occurred in the Ka0S SPLUNK Action workflow **${{ github.workflow }}**.
          **[KAOS SPLUNK]  Message:**
          \`\`\`
          **Please check the job logs for ${{ secrets.KAOS_ACTIONS_URL }}${{ github.run_id }}**
          \`\`\`
          **Workflow Name:** ${{ github.workflow }}
          **Job Name:** ${{ github.job }}
          **Run ID:** ${{ github.run_id }}
          **Run Number:** ${{ github.run_number }}
          **Repository:** ${{ github.repository }}
          **Branch:** ${{ github.ref }}
          **Commit:** ${{ github.sha }}
          Please investigate the issue.
          EOF
          )
          gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-title="$KAOS_ISSUE_TITLE" -f kaos-issue-body="$KAOS_ISSUE_BODY" -f kaos-issue-actions=create -f kaos-issue-tag="bug splunk"   

            