name: Ka0s Splunk

on:
    workflow_dispatch:
     inputs:
      kaos-issue-body-file:
        description: 'Attach file to body'
        default: ""
        required: true
      kaos-issue-id:
        description: 'Actions ID'
        default: ""
        required: true

permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write

env:
  GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
  KAOS_MODULE: "[Ka0S] SPLUNK"
  GH_REPO: ${{ secrets.KAOS_REPO }}
  GH_SPLUNK_URL: ${{ secrets.KAOS_SPLUNK_URL }}
  GH_SPLUNK_URL_IDX: ${{ secrets.KAOS_SPLUNK_URL_IDX }}
  GH_SPLUNK_USER: ${{ secrets.KAOS_SPLUNK_USER }}
  GH_SPLUNK_PASSWORD: ${{ secrets.KAOS_SPLUNK_PASSWORD }}
  
jobs:
  kaos-splunk:
    runs-on: kaos-runner-splunk

    steps:
      - id: repo # Checkout the repository to get the information of the commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_TOKEN }}

      - id: send-file-splunk
        run: |
          # Check url
          curl -v -k -s -d "username=$GH_SPLUNK_USER&password=$GH_SPLUNK_PASSWORD" "${{ env.GH_SPLUNK_URL }}en-US/services/auth/login"
          # Autenticación
          index_name='idx_kaos_github'
          # Obtener la clave de sesión
          curl -k -s -d "username=${{ env.GH_SPLUNK_USER }}&password=${{ env.GH_SPLUNK_PASSWORD}}" "${{ env.GH_SPLUNK_URL }}en-US/services/auth/login"
          session_key=$(echo $response | sed -n 's:.*<sessionKey>\(.*\)</sessionKey>.*:\1:p')
          # Leer el contenido del fichero
          file_path='${{ github.event.inputs.kaos-issue-body-file }}'
          data=$(cat $file_path)

          # Enviar datos al índice específico
          # KAOS_RESPONSE_IDX=$(curl -k -s -H "Authorization: Splunk $session_key" -d "$data" "${{ env.GH_SPLUNK_URL_IDX }}en_US/services/receivers/simple")
          curl -k -u admin:splunk/splunk -X POST "https://80.28.162.237:8089/services/receivers/stream?sourcetype=st_kaos_github&index=idx_kaos_github&host=curl-testing" -H "Content-Type: multipart/form-data" -F "file=@${{ github.event.inputs.kaos-issue-body-file }}"
      
  handle_failure:
    runs-on: 
      group: kaos-test
    needs: [kaos-splunk]
    if: ${{ failure() }}
    steps:
      - id: check-execution
        env:
          GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
        run: |
          echo "Error detected in Ka0S, creating issue..."
          KAOS_ISSUE_TITLE="Ka0S Action Failed: ${{ github.workflow }}"
          KAOS_ISSUE_BODY=$(cat <<'EOF'
          An error occurred in the Ka0S Action workflow **${{ github.workflow }}**.
          **${{ env.KAOS_MODULE }}  Message:**
          \`\`\`
          **Please check the job logs for ${{ secrets.KAOS_ACTIONS_URL }}${{ github.run_id }}**
          \`\`\`
          **Workflow Name:** ${{ github.workflow }}
          **Job Name:** ${{ github.job }}
          **Run ID:** ${{ github.run_id }}
          **Run Number:** ${{ github.run_number }}
          **Repository:** ${{ github.repository }}
          **Branch:** ${{ github.ref }}
          **Commit:** ${{ github.sha }}
          Please investigate the issue.
          EOF
          )
          gh workflow run issue.yaml --ref ${{ github.ref }} -f kaos-issue-title="$KAOS_ISSUE_TITLE" -f kaos-issue-body="$KAOS_ISSUE_BODY" -f kaos-issue-actions=create -f kaos-issue-tag="bug"   
