name: Ka0s Summary

on:
    workflow_dispatch:
    schedule:
      - cron: '0 0 * * *' # Ejecutar diariamente a medianoche

permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: write

jobs:
  kaos-summary:
    runs-on: kaos-self-hosted

    steps:
      - name: Checkout Repository
      # Checkout the repository to get the information of the commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.KAOS_TOKEN }}

      - name: Set Info about Commit temp vars
        # Set the branch name and team name and file implicit in commit and save it in the environment variable
        run: |
          BRANCH_NAME=${{ github.event.base_ref }}
          USER_NAME=${{ github.actor.name}}
          USER_EMAIL=${{ github.actor.email }}
          PATH_RESUME="observability/data/github/"
          KAOS_MODULE="[CORE SUMMARY]"
          KAOS_STEP_MODULE=""
          KAOS_WORKFLOW="splunk.yaml"
          echo "KAOS_WORKFLOW=$KAOS_WORKFLOW" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "USER_NAME=$USER_NAME" >> $GITHUB_ENV
          echo "USER_EMAIL=$USER_EMAIL" >> $GITHUB_ENV
          echo "PATH_RESUME=$PATH_RESUME" >> $GITHUB_ENV
          echo "KAOS_MODULE=$KAOS_MODULE" >> $GITHUB_ENV
          echo "KAOS_STEP_MODULE=$KAOS_STEP_MODULE" >> $GITHUB_ENV
          echo "DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Summary Issue Log
        env:
           GH_TOKEN: ${{ secrets.KAOS_ISSUE_TOKEN }}
           GH_REPO: ${{ secrets.KAOS_REPO }}
        run: |
            #  Extraemos toda la información de las issues haste el momento
            gh issue list --repo $GH_REPO --state all --json assignees,author,body,closed,closedAt,comments,createdAt,id,labels,milestone,number,projectCards,projectItems,reactionGroups,state,title,updatedAt,url > ${{ env.PATH_RESUME }}issue-log-${{ env.DATETIME }}.json
            # Formatear el archivo JSON final
            cat ${{ env.PATH_RESUME }}issue-log-${{ env.DATETIME }}.json | jq -s '.' > kaos-issue-log.json

      - name: Summary Workflows Log
        env:
           GH_TOKEN: ${{ secrets.KAOS_ISSUE_TOKEN }}
           GH_REPO: ${{ secrets.KAOS_REPO }}
        run: |
          # Añadimos la infpormación de todos los workflows y sus datos
          # Generamos el fichero con los workflows disponibles en el repo
          gh workflow list --all --json id,name,path,state > ${{ env.PATH_RESUME }}workflows-available-${{ env.DATETIME }}.json
          # Formatear el archivo JSON final
          cat ${{ env.PATH_RESUME }}workflows-available-${{ env.DATETIME }}.json | jq -s '.' > ${{ env.PATH_RESUME }}kaos-workflows-available.json
          # job_id=$(gh run list --workflow=$workflow --branch=main --json databaseId --jq '.[0].databaseId')
          # gh workflow run issue.yaml --ref main -f kaos-issue-title=$KAOS_ISSUE_TITLE -f kaos-issue-body="Launch workflow $workflow with id $job_id" -f kaos-issue-id=$GH_ISSUE_ID
          # A continuación extraemos el fichero con todas las ejecuciones de cada uno de los workflows anteriores
          # Leer el archivo de workflows
          workflows=$(cat ${{ env.PATH_RESUME }}kaos-workflows-available.json | jq -r '.[] | .[] | .id')  
          # Crear un archivo para guardar los detalles de las ejecuciones
          echo "[]" > ${{ env.PATH_RESUME }}workflows-runs-${{ env.DATETIME }}.json
          # Iterar sobre cada workflow y obtener sus ejecuciones
          for workflow_id in $workflows; do
          gh api repos/:owner/:repo/actions/workflows/$workflow_id/runs --paginate --jq '.workflow_runs[]' | jq '{
            id: .id,
            name: .name,
            head_branch: .head_branch,
            head_sha: .head_sha,
            run_number: .run_number,
            event: .event,
            status: .status,
            conclusion: .conclusion,
            workflow_id: .workflow_id,
            url: .url,
            created_at: .created_at,
            updated_at: .updated_at,
            run_started_at: .run_started_at
          }' >> ${{ env.PATH_RESUME }}workflows-runs-${{ env.DATETIME }}.json
          done

          # Formatear el archivo JSON final
          cat ${{ env.PATH_RESUME }}workflows-runs-${{ env.DATETIME }}.json | jq -s '.' > ${{ env.PATH_RESUME }}kaos-workflows-runs.json
      
      - name: Upload files to Repo
        env:
           GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
        run: |  
             # Al ser un proceso nocturno le vamos a añadir la funcionalidad de hacer push a la rama para integrar los ficheros
             git config --global user.email ${{ secrets.KAOS_USER_EMAIL }}
             git config --global user.name ${{ secrets.KAOS_USER_NAME }}
             git add ${{ env.PATH_RESUME }}kaos-*
             git commit -m "[KA0S] We integrate the summary files for ${{ env.DATETIME }} in the repository, you do not need to integrate these files"
             git push

             # Generamos los ficheros delta de kaos-workflows-runs
             if [[ -f "${{ env.PATH_RESUME }}kaos-workflows-runs-old.json" ]]; then
                 # Comparar con la lista anterior
                 jq -s '.[0] - .[1]' ${{ env.PATH_RESUME }}kaos-workflows-runs.json ${{ env.PATH_RESUME }}kaos-workflows-runs-old.json > ${{ env.PATH_RESUME }}kaos-workflows-runs-delta.json
                 if [[ -f "${{ env.PATH_RESUME }}kaos-workflows-runs-delta.json" ]]; then
                  # LLamamos a splunk
                  gh workflow run ${{ env.KAOS_WORKFLOW }} --ref main -f kaos-issue-body-file=${{ env.PATH_RESUME }}kaos-workflows-runs-delta.json -f kaos-issue-id=${{ github.workflow }}
                 else
                  echo "No hay contenido nuevo que subir a splunk"
                fi 
             else
                 cat ${{ env.PATH_RESUME }}kaos-workflows-runs.json > ${{ env.PATH_RESUME }}kaos-workflows-runs-old.json
                 cat ${{ env.PATH_RESUME }}kaos-workflows-old.json > ${{ env.PATH_RESUME }}kaos-workflows-runs-delta.json
                 gh workflow run ${{ env.KAOS_WORKFLOW }} --ref main -f kaos-issue-body-file=${{ env.PATH_RESUME }}kaos-workflows-runs-delta.json -f kaos-issue-id=${{ github.workflow }}
             fi

             # Generamos los ficheros delta de kaos-workflows-available
             if [[ -f "${{ env.PATH_RESUME }}kaos-workflows-available-old.json" ]]; then
                 # Comparar con la lista anterior
                 jq -s '.[0] - .[1]' ${{ env.PATH_RESUME }}kaos-workflows-available.json ${{ env.PATH_RESUME }}kaos-workflows-available-old.json > ${{ env.PATH_RESUME }}kaos-workflows-available-delta.json
                 if [[ -f "${{ env.PATH_RESUME }}kaos-workflows-available.-delta.json" ]]; then
                  # LLamamos a splunk
                  gh workflow run ${{ env.KAOS_WORKFLOW }} --ref main -f kaos-issue-body-file=${{ env.PATH_RESUME }}kaos-workflows-available-delta.json -f kaos-issue-id=${{ github.workflow }}
                 else
                  echo "No hay contenido nuevo que subir a splunk"
                fi 
             else
                 cat ${{ env.PATH_RESUME }}kaos-workflows-available.json > ${{ env.PATH_RESUME }}kaos-workflows-available-old.json
                 cat ${{ env.PATH_RESUME }}kaos-workflows-available-old.json > ${{ env.PATH_RESUME }}kaos-workflows-available-delta.json
                 gh workflow run ${{ env.KAOS_WORKFLOW }} --ref main -f kaos-issue-body-file=${{ env.PATH_RESUME }}kaos-workflows-available-delta.json -f kaos-issue-id=${{ github.workflow }}
             fi
             

             # Generamos los ficheros delta de kaos-issue-log
             if [[ -f "${{ env.PATH_RESUME }}kaos-issue-log-old.json" ]]; then
                 # Comparar con la lista anterior
                 jq -s '.[0] - .[1]' ${{ env.PATH_RESUME }}kaos-issue-log.json ${{ env.PATH_RESUME }}kaos-issue-log-old.json > ${{ env.PATH_RESUME }}kaos-issue-log-delta.json
                 if [[ -f "${{ env.PATH_RESUME }}kaos-issue-log-delta.json" ]]; then
                  # LLamamos a splunk
                  gh workflow run ${{ env.KAOS_WORKFLOW }} --ref main -f kaos-issue-body-file=${{ env.PATH_RESUME }}kaos-issue-log-delta.json -f kaos-issue-id=${{ github.workflow }}
                 else
                  echo "No hay contenido nuevo que subir a splunk"
                fi 
             else
                 cat ${{ env.PATH_RESUME }}kaos-issue-log.json > ${{ env.PATH_RESUME }}kaos-issue-log-old.json
                 cat ${{ env.PATH_RESUME }}kaos-issue-log-old.json > ${{ env.PATH_RESUME }}kaos-issue-log-delta.json
                 gh workflow run ${{ env.KAOS_WORKFLOW }} --ref main -f kaos-issue-body-file=${{ env.PATH_RESUME }}kaos-issue-log-delta.json -f kaos-issue-id=${{ github.workflow }}
             fi

      - name: Upload parameter file
        uses: actions/upload-artifact@v4
        with:
          name: reports-summary-files
          path: |
            ${{ env.PATH_RESUME }}kaos-issue-log-delta.json
            ${{ env.PATH_RESUME }}kaos-workflows-runs-delta.json
            ${{ env.PATH_RESUME }}kaos-workflows-available--delta.json
      
      - name: Check execution
        env:
          GH_TOKEN: ${{ secrets.KAOS_TOKEN }}
          GH_ISSUE_ID: ${{ vars.KAOS_ISSUE_ID }}
        if: failure()
        run: |
          echo "Error detected in KaoS INIT, creating issue..."
          KAOS_ISSUE_TITLE="${{ env.KAOS_MODULE }} Action Failed: ${{ github.workflow }}"
          KAOS_ISSUE_BODY=$(cat <<'EOF'
          An error occurred in the ${{ env.KAOS_MODULE }} Action workflow **${{ github.workflow }}**.
          **[KAOS INIT]  Message:**
          \`\`\`
          **Please check the job logs for ${{ secrets.KAOS_ACTIONS_URL }}${{ github.run_id }}**
          \`\`\`
          **Workflow Name:** ${{ github.workflow }}
          **Job Name:** ${{ github.job }}
          **Run ID:** ${{ github.run_id }}
          **Run Number:** ${{ github.run_number }}
          **Repository:** ${{ github.repository }}
          **Branch:** ${{ github.ref }}
          **Commit:** ${{ github.sha }}
          **Files Involved:**
          ${{ env.INVOLVED }}
          Please investigate the issue.
          EOF
          )
          gh issue create --title "$KAOS_ISSUE_TITLE" --body "$KAOS_ISSUE_BODY" --label "bug,core" --repo ${{ github.repository }}
  
  