name: Test

on:
  workflow_dispatch:
    # This workflow runs only on the feature branch
    branches:
      - feature

permissions:
  # This workflow has write permissions to the contents of the repository
  contents: write
  actions: write

jobs:
  test-github-action:
    # This job runs on the latest version 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      # This action checks out the repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set execution date-time variable
        id: set_datetime
        run: echo "datetime=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Set up act
        run: |
          curl -s https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
          
      - name: Validate GitHub Actions workflow
        run: |
          echo "Validating workflow..."
          act -version
          act -h
          act -W .github/workflows -j init > results/Resume-execution-test-${{ env.datetime }}.txt 2>&1 || exit 1
      
      - name: Commit and Push Results
      # This action commits and pushes the results to the repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add results/*.txt
          git commit -m "Build: TEST of GitHub Actions ${{ env.CLEAN_BRANCH_NAME }} cheked"
          git push origin feature
    
      - name: Trigger Audit
      # This action triggers the Audit workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Audit
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: feature