name: Version Actions MarketPlace

on:
  workflow_dispatch:
    # Este flujo de trabajo se ejecuta solo en la rama feature

permissions:
  # Este flujo de trabajo tiene permisos de escritura en el contenido del repositorio
  contents: write
  actions: write

jobs:
  web-scrapping:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener token de acceso de GitHub
        uses: actions/checkout@v4

      - name: Utilizar API de GitHub para obtener información sobre acciones
        run: |
          curl -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: token ${{ secrets.MARKETPLACE }}" \
               "https://api.github.com/marketplace_listing/plans?verified=true" -o marketplace-update.json

      - name: Grabar información en un fichero
        uses: actions/upload-artifact@v4
        with:
          name: marketplace-update.json
          path: marketplace-update.json
