
services:
  kaos-forwarder-observability:
    networks:
      default:
        aliases:
          - kaos-uf-1
    image: ${UF_IMAGE:-splunk/universalforwarder:latest}
    hostname: kaos-uf-1
    container_name: kaos-uf-1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_STANDALONE_URL=so1
      - SPLUNK_ADD=udp 1514,monitor /var/log/*
      - SPLUNK_PASSWORD
    ports:
      - 8089:8089
    restart: always
    volumes:
      - kaos-uf-1-local:/logs
      - kaos-uf-12-local:/tmp
      - /home/santakloud/github/kaos:/kaos:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./default.yml:/tmp/defaults/default.yml
  kaos-splunk-core:
    networks:
      default:
        aliases:
          - kaos-so-1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    hostname: kaos-so-1
    container_name: kaos-so-1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_STANDALONE_URL=so1
      - SPLUNK_PASSWORD
    ports:
      - 8008:8000
      - 8090:8090
      - 9997:9997
    restart: always
    volumes:
      - kaos-so-1-local:/opt/splunk/etc
      - kaos-so-12-local:/opt/splunk/var
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./default.yml:/tmp/defaults/default.yml
  kaos-splunk-cluster-manager:
      networks:
        default:
          aliases:
            - kaos-cm-1
      image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
      hostname: kaos-cm-1
      container_name: kaos-cm-1
      environment:
        - SPLUNK_START_ARGS=--accept-license
        - SPLUNK_INDEXER_URL=kaos-idx-1,kaos-idx-2
        - SPLUNK_SEARCH_HEAD_URL=kaos-so-1
        - SPLUNK_CLUSTER_MASTER_URL=kaos-cm-1
        - SPLUNK_ROLE=splunk_cluster_master
        - SPLUNK_PASSWORD
      ports:
        - 8009:8009
        - 8091:8091
      restart: always
      volumes:
        - kaos-cm-1-local:/opt/splunk/etc
        - kaos-cm-12-local:/opt/splunk/var
        - ./default.yml:/tmp/defaults/default.yml
  kaos-splunk-idx-1:
    networks:
      default:
        aliases:
          - kaos-idx-1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    hostname: kaos-idx-1
    container_name: kaos-idx-1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=kaos-idx-1,kaos-idx-2
      - SPLUNK_SEARCH_HEAD_URL=kaos-so-1
      - SPLUNK_CLUSTER_MASTER_URL=kaos-cm-1
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_PASSWORD
    ports:
      - 8010:8010
      - 8092:8092
    restart: always
    volumes:
      - kaos-idx-1-local:/opt/splunk/etc
      - kaos-idx-12-local:/opt/splunk/var
      - ./default.yml:/tmp/defaults/default.yml
  kaos-splunk-idx-2:
    networks:
      default:
        aliases:
          - kaos-idx-2
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    hostname: kaos-idx-2
    container_name: kaos-idx-2
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_INDEXER_URL=kaos-idx-1,kaos-idx-2
      - SPLUNK_SEARCH_HEAD_URL=kaos-so-1
      - SPLUNK_CLUSTER_MASTER_URL=kaos-cm-1
      - SPLUNK_ROLE=splunk_indexer
      - SPLUNK_PASSWORD
    ports:
      - 8011:8011
      - 8093:8093
    restart: always
    volumes:
      - kaos-idx-1-local:/opt/splunk/etc
      - kaos-idx-12-local:/opt/splunk/var
      - ./default.yml:/tmp/defaults/default.yml


volumes:
  kaos-so-1-local:
  kaos-so-12-local:
  kaos-uf-1-local:
  kaos-uf-12-local:
  kaos-cm-1-local:
  kaos-cm-12-local:
  kaos-idx-1-local:
  kaos-idx-12-local:
  kaos-idx-2-local:
  kaos-idx-22-local: