
services:
  kaos-forwarder-observability:
    networks:
      default:
        aliases:
          - kaos-uf-1
    image: ${UF_IMAGE:-splunk/universalforwarder:latest}
    hostname: kaos-uf-1
    container_name: kaos-uf-1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_STANDALONE_URL=so1
      - SPLUNK_ADD=udp 1514,monitor /var/log/*
      - SPLUNK_PASSWORD
    ports:
      - 8089:8089
    restart: always
    volumes:
      - kaos-uf-1-local:/logs
      - kaos-uf-12-local:/tmp
      - /home/santakloud/github/kaos:/kaos:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  kaos-splunk-core:
    networks:
      default:
        aliases:
          - kaos-so-1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    hostname: kaos-so-1
    container_name: kaos-so-1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_STANDALONE_URL=so1
      - SPLUNK_PASSWORD
    ports:
      - 8008:8000
      - 8090:8090
      - 9997:9997
    restart: always
    volumes:
      - kaos-so-1-local:/opt/splunk/etc
      - kaos-so-12-local:/opt/splunk/var
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
volumes:
  kaos-so-1-local:
  kaos-so-12-local:
  kaos-uf-1-local:
  kaos-uf-12-local: